<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
{{--<script src="{{ asset(mix('js/jquery.min.js')) }}"></script>--}}
{{--<script src="{{mix('js/bootstrap.min.js')}}"></script>--}}
{{--<script src="{{mix('js/swiper.min.js')}}"></script>--}}
{{--<script src="{{mix('js/isotope.min.js')}}"></script>--}}
{{--<script src="{{mix('js/fancybox.min.js')}}"></script>--}}
{{--<script src="{{mix('js/odometer.min.js')}}"></script>--}}
{{--<script src="{{mix('js/isotope.min.js')}}"></script>--}}
{{--<script src="{{mix('js/scripts.js')}}"></script>--}}
<script src="{{mix('js/merged.js')}}"></script>
